### ISSUE TITLE
about merge two word documents question

### ISSUE THREAD

**Issue by aa294828045** [PHPOffice/PHPWord#1130]
Hi.
   How to merge two word documents？
   Existing API doesn't seem to be able to do that.

**Comment by FBnil** [comment]
Is merge putting one document after the other?

Indeed, phpword does not have this, but it contains functions which you can use to cut from the `<w:body>` to `</w:body>` in the second document, and inject that just before the  `</w:body>` in the first document.

The reality is that it is a little bit more complex, as, for example, the image1 of the second document needs to be renamed so that it does not overwrite the image1 in the first document, so you need to do lots of code before you have something working.

So the first hurdle is accessing the internal XML strings from the docx document.

```
class OpenTemplateProcessor extends \PhpOffice\PhpWord\TemplateProcessor
{
    public function __construct($instance)
    {
        return parent::__construct($instance);
    }

    public function __get($key)
    {
        return $this->$key;
    }

    public function __set($key, $val)
    {
        return $this->$key = $val;
    }
}
```
Now you are able to access tempDocumentMainPart, like so:
```
$templateProcessor = new OpenTemplateProcessor($file_dir);
dd($templateProcessor->tempDocumentMainPart);
```
With which you can proceed as described.

And injecting the images from document2 into document1 `$templateProcessor->zipClass->AddFromString(word/media/image2.jpeg", $binarystring)`

**Comment by FBnil** [comment]
You can also read this discussion: https://github.com/PHPOffice/PHPWord/issues/8

**Comment by pfleu** [comment]
Using class OpenTemplateProcessor as explained by FBnil, a simple working example keeping header, footer and images from main template and inserting only text from other template:
`
$mainTemplateProcessor = new OpenTemplateProcessor('path/to/file);
$mainTemplateProcessor ->setValue('var_name', $value);

$innerTemplateProcessor = new OpenTemplateProcessor('path/to/other_file');
$innerTemplateProcessor->setValue('var2_name', $value2);

// extract internal xml from template that will be merged inside main template
$innerXml = $innerTemplateProcessor->__get('tempDocumentMainPart');
$innerXml = preg_replace('/^[\s\S]*<w:body>(.*)<\/w:body>.*/', '$1', $innerXml);
// remove tag containing header, footer, images
$innerXml = preg_replace('/<w:sectPr>.*<\/w:sectPr>/', '', $innerXml);
// inject internal xml inside main template 
$mainXml = $mainTemplateProcessor->__get('tempDocumentMainPart');
$mainXml = preg_replace('/<\/w:body>/', '<w:p><w:r><w:br w:type="page" /><w:lastRenderedPageBreak/></w:r></w:p>' . $innerXml . '</w:body>', $mainXml);
$mainTemplateProcessor->__set('tempDocumentMainPart', $mainXml);

$mainTemplateProcessor->saveAs('path/result/file');
`
