### ISSUE TITLE
setValue a bold string with setOutputEscapingEnabled(true)

### ISSUE THREAD

**Issue by ddmo** [PHPOffice/PHPWord#1154]
Hi, I need to set \PhpOffice\PhpWord\Settings::setOutputEscapingEnabled(true).
When I try to set a bold value with setValue (in a template) with: 

`$template->setValue('TEXT' , '</w:t></w:r><w:r><w:rPr><w:b/></w:rPr><w:t xml:space="preserve">TEXT</w:t></w:r><w:r><w:t>');
`

The processor insert a plain string with like "</w:t></w:r><w:r><w:rPr><w:b/></w:rPr><w:t xml:space="preserve">TEXT</w:t></w:r><w:r><w:t>" not "**TEXT**".

Another way to insert a bold value with setValue and setOutputEscapingEnabled set to true?
Thanks

**Comment by FBnil** [comment]
@ddmo 

0. Why can't you set it to false, use setValue() then set it back to true?
1. You edit your template with word/writer and make the macro bold. Then the replaced text will be bold. Easiest solution.
2. You want to use blocks, where you actually cut the whole  w:p (because blocks only cut at paragraphs), and use phpWord() to make a nice valid xml. 
3. you use segments, which are not available yet. get the `replaceSegment('${TEXT}', 'w:r', '<w:b/>'.getSegment('${TEXT}', 'w:r')` to inject the `<w:b/>`.
4. You create a subclass with open access to the private variables and functions, and do not call setValue, but the internal `setValueForPart()`, which skips the escaping of `<` and `>`.

For solution 2:
```
	$phpWord = new \PhpOffice\PhpWord\PhpWord();
	$section = $phpWord->addSection();
	$text = $section->addText('TEXT', ['bold' =>false]);
	$objWriter = \PhpOffice\PhpWord\IOFactory::createWriter($phpWord, 'Word2007');
	$fullXml = $objWriter->getWriterPart('Document')->write();
```
Then you need to gut out the XML to cut the whole `<w:p>` to be able to `replaceBlock()` it. 

for solution 4:
```
class OpenTemplateProcessor extends \PhpOffice\PhpWord\TemplateProcessor
{
    protected $_instance;

    public function __construct($instance) {
		return parent::__construct($instance);
    }

    public function __call($method, $args) {
        return call_user_func_array(array($this->_instance, $method), $args);
    }

    public function __get($key) {
        return $this->$key;
    }

    public function __set($key, $val) {
        return $this->$key = $val;
    }
}

$templateProcessor = new OpenTemplateProcessor($file_dir);
$templateProcessor->tempDocumentMainPart = $templateProcessor->setValueForPart($search, $replace, $templateProcessor->tempDocumentMainPart, 1);
```

If this is helpful and saved you time, consider donating your time to expand the documentation.

**Comment by ddmo** [comment]
Thanks a lot FBnil! I've resolved with solution 1.
Have a nice day

**Comment by FBnil** [comment]
@ddmo Glad I could help. Please close the issue when you have the time.
