### ISSUE TITLE
[Bug] Wrong images in media when creating multiple Word documents

### ISSUE THREAD

**Issue by mariahaubner** [PHPOffice/PHPWord#1313]
This is a bug report

# Expected Behavior

When creating multiple Word-Documents with images as content, each document should contain the correct images.

### Current Behavior

Example: Create three documents. The first document contains one image in its body, the second has two images and the third has three images in the body.
The result will be, that the first document displays the correct image. The second document will display the image from the first document and one correct image. The third document will display the images from document one and two.

### Failure Information

This stems from a static call to Media in /PhpWord/Element/AbstractElement.php, Line 319 (version 0.13).
A call to `Media::resetElements();` before creating a new instance of PhpWord solved the problem for me.

PS.: my code makes it difficult to provide a code example to reproduce. But the static call still exists in version 0.14 /PhpWord/Element/AbstractElement.php, Line 395)

**Comment by troosan** [comment]
Indeed, those static variables are not a good idea, it means all instances of PhpWord share the same media, style, settings.
I could of course call `Media::resetStyles()` and `Style::resetStyles()` but that means the first document should be written to disk before creating a new instance of PhpWord, otherwise all Media and Styles will be lost. But I guess that's acceptable.
The best solution would of course be to have an instance of Media, Style and Settings inside PhpWord, this way each document carries its own, but that's a bit more work :-(

**Comment by mariahaubner** [comment]
Personally, I don't think that this bug will lead to issues with the majority of PHPWord users. Maybe just keep it in mind so when there is some reason for a bigger rewrite, this can be solved as well :)

**Comment by troosan** [comment]
fixed on develop branch
