### ISSUE TITLE
Allow to add Element at given index

### ISSUE THREAD

**Issue by nguyenk** [PHPOffice/PHPWord#1489]
This is:

- [ ] a bug report
- [X] a feature request
- [ ] **not** a usage question (ask them on https://stackoverflow.com/questions/tagged/phpword)

### Expected Behavior

I would very like to add a child element to a container (let's say a `Section`) with the following code : 
`$section->addElement($newElement, $index);`
or
`$section->addTextRun($newTextRun, $index);`

### Current Behavior

For now, I haven't seen any way to achieve this I tried to call `AbstractElement::setElementIndex()` but this will not update the order in the parent section. Maybe I missed something.

**Comment by nguyenk** [comment]
Hello @CyferZ thank you for the reminder. Honeslty I dont remember if I found a workaround, Ill try to check the code if this project.

But I think I will close it anyway as I might be the only one requesting the feature :)

Cheers

**Comment by CyferZ** [comment]
@nguyenk All good! :) If you like, or for someone else's reference, I came up with a workaround a moment ago for something I needed as well. I adjusted it in my response now for your case.

You'll need to create a custom class that extends the Container that you need to add an element to, eg. adding an Element to a Section which inherits from AbstractContainer. I will use Section as the example since it's most likely to be the more common container that is used.

```
class SectionControl extends Section {
    protected $phpWord;
    protected $section;
    
    public function __construct(PhpWord $phpWord, $sectionIndex = null) {
        $this->phpWord = $phpWord;
        
        $sections = $phpWord->getSections();
        
        if (is_null($sectionIndex)) {
            $this->section = $sections[count($sections) - 1];
        } else {
            $this->section = $sections[$sectionIndex];
        }
    }
    
    public function addNewElement($element, $index) {
        $element->setParentContainer($this->section);

        if (is_null($index)) {
            $element->setElementIndex($this->section->countElements() + 1);
        } else {
            $elements = $this->section->getElements();

            $initial = array_splice($elements, 0, $index - 1);
            $initial[] = $element;

            /** @var \PhpOffice\PhpWord\Element\AbstractContainer[] $newElementsArray Type hint */
            $newElementsArray = $initial + $elements;

            for ($k = 0; $k < count($newElementsArray); $k++) {
                $newElementsArray[$k]->setElementIndex($k + 1);
            }
        }

        $element->setElementId();

        $this->section->elements[] = $element;
    }
}
```

I haven't tested it myself just yet, but the theory is there.
I'll give it a go later to verify and perhaps edit if need be.
