### ISSUE TITLE
Add table into template

### ISSUE THREAD

**Issue by NielDuysters** [PHPOffice/PHPWord#2014]
I have a template .docx file in which I want to place a table. I can already read-in the template file and search-and-replace simple strings in the template.

But now I want to put a table in the template.

This is my code:
```php
$templateProcessor = new \PhpOffice\PhpWord\TemplateProcessor($template);
            $phpWord = new \PhpOffice\PhpWord\PhpWord();

            $templateProcessor->setValue('customer_name', $name); 
            $templateProcessor->setValue('customer_address', $address); 
            $templateProcessor->setValue('customer_city', $city); 
            $templateProcessor->setValue('customer_name', $name); 
            $templateProcessor->setValue('invoice_date', $date); 

            $table_section = $phpWord->addSection();
            $rows = 10;
            $cols = 5;
            $table_section->addText('Basic table', "rofl");

            $table = $table_section->addTable();
            for ($r = 1; $r <= $rows; $r++) {
                $table->addRow();
                for ($c = 1; $c <= $cols; $c++) {
                    $table->addCell(1750)->addText("Row {$r}, Cell {$c}");
                }
}

            $objWriter = new PhpOffice\PhpWord\Writer\Word2007($phpWord);
            $tableStr = $objWriter->getWriterPart('Document')->getTableAsText($table);

            $templateProcessor->setValue('product_table', $tableStr); 


            $templateProcessor->saveAs($new_file_path);
```

I have added this:
```
/* CUSTOM FUNCTION */
    function getTableAsText($element) {
        $xmlWriter = $this->getXmlWriter();
        $writer = new \PhpOffice\PhpWord\Writer\Word2007\Element\Table($xmlWriter, $element);
        $writer->write();
        return $xmlWriter->getData();
    }
```

to `PhpWord/Writer/Word2007/Part/Document.php`.

As output I just get all the rows as a paragraph, not at all as a table...

**Comment by troosan** [comment]
De comment here #2015

**Comment by ticelso** [comment]
Hello good morning.
Happy New Year to everyone there.
I am trying to implement the table in my template and I am following your tutorial.
It turns out that I received the following error message:
Fatal error: Uncaught Error: Call to undefined method PhpOffice\PhpWord\Writer\Word2007\Part\Document::getTableAsText() in
Is the function deprecated?
Thank you.

Versão em português:
Olá bom dia. 
Feliz ano novo para todos ai.
Estou tentanto inplementar a tabela no meu template e estou seguindo seu tutorial.
Ocorre que recebi a seguinte mensagem de erro:
Fatal error: Uncaught Error: Call to undefined method PhpOffice\PhpWord\Writer\Word2007\Part\Document::getTableAsText() in
Está depreciada a função?
Obrigado.
