### ISSUE TITLE
Images produced by addImage look different in Word for Windows and Word for Mac

### ISSUE THREAD

**Issue by cocorem** [PHPOffice/PHPWord#224]
Hi
I want to put image png  on my doc I try with or without table.

But I open the doc with 2 differents Word and the look it's not the same for the 2 documents
How I can fix it?
Thanks

**Comment by klompenrunner** [comment]
I have the same problem with images. Anything I can do to help / test / try?

I have not tried, but I scale my images from inch to pixels by multiplying inches * 96; which is too big in Mac.  I bet inches * 72 would be a perfect fit for Mac.

**Comment by mattdelashaw** [comment]
im experiencing the same thing. ive checked the xml of the same document generated on a windows machine using word 2007, and a mac using 2011, but i see no difference in the xml. i believe this is referenced already, but mac 2011 calls pixels, "points". the images are enlarged by 133% which is what you get when you divide the pixel by point, 96/72. 

because width and height can only be set by pixels, the mac version craps the bed.
