### ISSUE TITLE
XAMPP with PHP 5.3.1

### ISSUE THREAD

**Issue by samlinux** [PHPOffice/PHPWord#236]
HI is there a reason why the Sample_01_SimpleText.php example not work with the following configuration:
- XAMPP with PHP 5.3.1

But the all requirements seems to work:

Requirements
PHP 5.3.0 ... passed
PHP extension ZipArchive ... passed
PHP extension XML ... passed
PHP extension GD (optional) ... passed

Thanks for any help

**Comment by mdupont** [comment]
Out of curiosity, I tried running PHPWord Sample_01_SimpleText.php under XAMPP 1.7.3 (PHP 5.3...). So in 2019, **PHPWord doesn't even start under PHP 5.3**, due to some dependencies using the short array syntax (which appeared in PHP 5.4). The first one to trigger a syntax error was guzzlehttp/promise.

So it appears that the modern PHPWord only supports PHP 5.4+ anyway. I tried with PHP 5.4, everything worked fine and the resulting file displayed OK in Word.
