### ISSUE TITLE
Paragraph style hanging 

### ISSUE THREAD

**Issue by mburton603** [PHPOffice/PHPWord#358]
The hanging option does not work for paragraphs in Word2007 or RTF. One, it generates a first line indent rather than a hanging indent, and two, the amount of the indent is completely wrong - for example, setting a twips value of 1/2 inch was calculated as 4.09 inches.

**Comment by cmette** [comment]
yes - it seems true
...but nobody fix it!? If you want to fix it in your local file, 

edit PhpOffice\PhpWord\Style\Paragraph.php about the line 182

    public function setStyleValue($key, $value)
    {
        $key = String::removeUnderscorePrefix($key);
        if ($key == 'indent' || $key == 'hanging') {
          $value = $value * 720;
        } elseif ($key == 'spacing') {
            $value += 240; // because line height of 1 matches 240 twips
        }

        return parent::setStyleValue($key, $value);
    }

and set the 720 to 0

    $value = $value * 720;

or delete the whole line

**Comment by mdupont** [comment]
I just had to work with hanging indents with version 0.17.0 and Word 2007 output. Here is the current status:

- The documentation is wrong. https://phpword.readthedocs.io/en/latest/styles.html#paragraph says `hanging` and `indent` and not in twip, they are in half-inches (see the snippet above which shows the passed value is multiplied by 720).  
As to why this is the case, no idea, it has been this way since the Paragraph.php file was created in 2014.
- You have to specify both `indent` and `hanging` values to have the hanging indent working correctly, setting `hanging` only did not work as expected.
