### ISSUE TITLE
Special Characters (ampersand) in Title break docx output

### ISSUE THREAD

**Issue by jonnsn** [PHPOffice/PHPWord#401]
Hi,

if you change Sample_17_TitleTOC.php to add a title including an &-sign
```PHP
$section->addTitle('Foo & Bar', 1);
```
and select docx-Result the document won't open (tested in Word 2013):
"The file ____ cannot be opened because of problems with the contents"
Details: "Invalid char" 
Position: [position of the ampersand in document.xml]

I did not test this with other characters but there might also be problems with [",',< and >](http://en.wikipedia.org/wiki/List_of_XML_and_HTML_character_entity_references#Predefined_entities_in_XML)

I found [this post](http://stackoverflow.com/a/13222304) which might indicate the problem.
Escaping the character does not really help (see the StackOveflow-Thread linked above).

If I find some time I will try to solve this issue and make a patch, but I just wanted to note it down here already. Maybe someone has a note or already solved it somehow :-)

Regards

**Comment by MaxiBul** [comment]
@RomanSyroeshko 
Looks like not fully fixed. Same problem we have at Writer/Word2007/Element/Text.php:48
This is strange place. Here we write text in tag <w:t> using $this->getText(), which uses String::controlCharacterPHP2OOXML, which convert special symbols to something like _x00010000_. Microsoft made this format for "Encode and Decode XML Element and Attribute Names". Did it work with element values? And there is no any work with ampersand.

**Comment by RomanSyroeshko** [comment]
Hi, @MaxiBul. Thanks for pointing this out. Does it cause any issues: generated document is broken or whatever?

**Comment by MaxiBul** [comment]
Yes, generated document is broken without this fix. Same result, as in first post.

**Comment by RomanSyroeshko** [comment]
What if you replace ``$xmlWriter->writeRaw($this->getText($element->getText()))`` with ``$xmlWriter->writeRaw($element->getText())`` in ``PhpOffice\PhpWord\Writer\Word2007\Element\Text`` and escape string you pass to ``Text`` outside of it? Will it help you?

I mean, if you say that ``controlCharacterPHP2OOXML`` function call is useless here, lets exclude it and see what happens next. Yet, please, don't forget escape strings you pass to PHPWord methods, because all escaping must be done outside of the library since 0.12.0.

**Comment by MaxiBul** [comment]
I little confused with "all escaping must be done outside of the library". PHPWord support export result in different formats (docx, pdf,...). Each format has own rules of character escaping. In result if I need result in 2 different formats, I need learn each required format and create 2 documents with different escaping? Do you think this is normal? Or I miss something? If library has different functions for export in different formats, why it can't prepare data for each format?

**Comment by RomanSyroeshko** [comment]
OK, lets align our terminology first. What do you mean under "escaping"? Simple ``htmlspecialchars`` method call?

**Comment by MaxiBul** [comment]
under "escaping" I mean:
- for MS XML text between tags = htmlspecialchars(), for example;
- for MS XML tag names/attributes = to characters like _x00010000_;
- for C string = backslash before special character;
...

**Comment by GMTA** [comment]
Hi Roman, commit b2286f85 made PHPWord completely broken for all Word documents that have the ampersand ('&') character anywhere in the body of the document, as opposed to being broken only for that character residing in the title of the document.

You said the following: "PHPWord code is not responsible for text escaping."

I sincerely hope that you don't mean that PHPWord is not responsible for proper output escaping. If I supply a valid UTF-8 string to PHPWord, PHPWord should apply proper escaping based on the output location. So if it ends up as the contents for an XML element, you apply XML character escaping. If it ends up in HTML, you apply HTML character escaping. If you don't do this, you will effectively create a broken library.

Please apply MaxiBul's suggestions for output escaping.

**Comment by RomanSyroeshko** [comment]
@GMTA, what's the problem? Have you read our release notes? Have you reviewed the changes before applying the new version of PHPWord? Did you try escaping strings BEFORE you pass them to the library?

**Comment by GMTA** [comment]
@RomanSyroeshko, the problem is that "All text escaping must be performed out of the library" is a crazy requirement for you to give your users. You are building a library which is capable of many different output formats. I've never heard of a (decent) library that requires you to perform your own output escaping based on what you use.

I could give you tons of reasons why PHPWord should apply output escaping, apart from this issue of course. For example, if you were to implement auto TOC generation based on titles (I don't know if you already support this), which kind of escaping do you expect your users to apply? XML escaping? TOC-specific escaping? Your users don't know and don't care, they just want to pass valid Unicode data and expect you to take care of proper output formatting.

Another reason: it would be impossible for your users to create a single document and then output it as PDF, DOCX, etc. in one single run. They would have to reconstruct the entire document based on the output format.

And another: you would need to document every possible kind of output the input strings are going to be used for, which is way more work than just saying "pass me UTF-8".

I've worked with a lot of wide-spread libraries, and none of them require you to perform escaping yourself. Unless you want to actively prevent PHPWord from being used, I strongly recommend you to reconsider your opinion on escaping.

As far as issue #51 goes, you say:
> There are also libraries which help to build HTML pages. So, if we escape data before submitting to HTML builders, why not to escape data before submitting to PhpWord?

This is just nonsense. Almost all HTML builders apply escaping themselves; you don't need to escape your strings yourself. And even then: most HTML builders have a single output format. The PHPWord library is obviously meant to support multiple output formats.

> Just escape data out of the library. Remember: escape once, use multiple times. :)

This is really bad advice. If you pre-escape your data, you effectively make it impossible to use that data for other output targets without possibly corrupting the original string. You should escape your data as soon as it **cannot** be used in any other way, which is **not** the case in PHPWord.

> Morever, there is no need to implement the same escaping functionality in all libraries for all formats of documents.

Agreed - so just depend on one of the many escaping libraries available for PHPWord if that is your issue.

Want more reasons? [Here is an article.](http://lukeplant.me.uk/blog/posts/why-escape-on-input-is-a-bad-idea/)
Have questions about implementing output escaping in PHPWord? Please just ask me. It's not that hard.

**Comment by GMTA** [comment]
@RomanSyroeshko Please stop deleting my comments. You know that people get email notifications of these, right? And my [activity feed](https://github.com/GMTA?tab=activity) still contains those comments?

I gave you a number of reasons why your current direction on output escaping for PHPWord is just plain wrong. Please supply counter arguments if you think **I'm** wrong. Again, please read this [informative article](http://lukeplant.me.uk/blog/posts/why-escape-on-input-is-a-bad-idea/) for more information.

Trying to hide critique is a bit dictator-y, if you ask me.

**Comment by RomanSyroeshko** [comment]
Your comment was aggressive, not constructive and you didn't answer my questions. Such comments will be deleted in future too.

**Comment by GMTA** [comment]
I do not think it was aggressive - I answered your questions, I gave reasons why the new course for PHPWord output escaping would be a mistake and even offered you help and referenced you to further reading material.

Could you please respond to this issue though? We still do not know if you plan to stick with this new course or plan to change PHPWord in such a way that it becomes a library that can generate valid Word documents without requiring its users to perform escaping themselves?

**Comment by RomanSyroeshko** [comment]
We consider introducing escaping components in the next release. For now escaping must be done by user. If you don't like this, continue using v0.12.0.

@MaxiBul, thanks for the given rules.

**Comment by lanre-ade** [comment]
@RomanSyroeshko @GMTA 
I found this StackOverflow post very helpful in overcoming the issue with escaping special characters (particularly the custom `xmlEntities` function in the second response). Hopefully someone else can benefit from this information too

**Comment by playmono** [comment]
Totally agree with @GMTA . Programming as Spanish developer with this tool is completely crazy. If escaping is a core-must to make it work the library. Why the library does not provide good methods to do it?

**Comment by lrigdon** [comment]
Based on comments in gethub (https://github.com/PHPOffice/PHPWord/issues/514) I changed my process to replace &amp; in the text that I'm feeding phpword with &amp;amp; and it works.  That gets me past this issue for now.

**Comment by judgej** [comment]
This is crazy - the application is responsible for escaping *text* passed in through methods that accept *text* based on some internal use of that *text* which the application does not get involved in? What the hell? Really?

**Comment by mjpelmear** [comment]
Just adding another comment to the pile.
Dealing with special characters in this manner is just *wrong*.
Why is there such resistance to handling it within the library?

**Comment by judgej** [comment]
I suspect it comes down to what level of abstraction is being applied to this library. On one hand the author looks at it as a library to help being do stuff with the the XML that makes up a document, so the XML kind of bleeds out of it. On the other hand, since it has multiple output formats, it is seen as a generic document generation tool, some document types of which have no relation to XML whatsoever. So it's all a but confused.

@mjpelmear IMO You are right - the level of abstraction that applications using using the library should be dealing with is *not* XML - not even in the slightest bit XML. However, those applications should be able to extend the XML *layer* that converts the generic document objects into an XMLDOC stream, so that additional features can be added at that level and only affect the XML generation and not rtf documents, and of course plug into the various *different* XML document types separately.

For example, adding tabs to a header involves some horrible hacks in the application - inserting different special characters depending on what the known output format is going to be (e.g. escape sequences for RDF, closing tags and inserting other elements then reopening tags again for XMLDOC, and completely different XML hacks for OpenXML).

The problem in solving this is that the library has evolved the way it has because (I suspect) it has been quite a journey of discovery - there is very little information out there that makes real sense of these document formats. However, having done that, starting again with lessons learnt, and a more formal layered approach is needed to lead on to a more maintainable library. That's a lot of work though, so we are stuck here. I don't want to put down the fantastic effort put into this library so far - I really don't. I do think it is standing at a crossroads though. That's just my personal feeling about it.

**Comment by phpdave** [comment]
This feelings weird
```
\PhpOffice\PhpWord\Settings::setOutputEscapingEnabled(true);
```

I feel like it should be
```
$this->_phpWord = new \PhpOffice\PhpWord\PhpWord();
$this->_phpWord->getSettings()->setOutputEscapingEnabled(true);
```
But I guess for some reason doing a static class was decided.  Its just hard to know what PHPWord can do when things aren't connected.

**Comment by chrisribe** [comment]
Thanks for the comment @mjpelmear, helped solve my issues !

> Just adding another comment to the pile.
> Dealing with special characters in this manner is just _wrong_.
> Why is there such resistance to handling it within the library?
> 
> edit:
> It looks like this was finally given a half-hearted response.
> If you ran into problems with characters not being escaped, go look at **\PhpOffice\PhpWord\Settings::setOutputEscapingEnabled(true);**

**Comment by chrisribe** [comment]
Dang spoke too soon, was still causing issues.

1. The escape flag is only used on write, was having issues since I need it to occur before write.
