### ISSUE TITLE
AddHTML & or &amp; breaks

### ISSUE THREAD

**Issue by klompenrunner** [PHPOffice/PHPWord#514]
Taken from: Sample_26_Html.php

The sample works:
'&lt;p&gt;Some well formed HTML snippet needs to be used&lt;p&gt;';

Bad HTML like this as expected breaks the XML:
'&lt;p&gt;Some well formed HTML snippet needs &amp; to be used&lt;p&gt;';

When I add an HTML ampersand it breaks the XML too:
'&lt;p&gt;Some well formed HTML snippet needs &amp;amp; to be used&lt;p&gt;';

But double escaping the ampersand makes it work.
'&lt;p&gt;Some well formed HTML snippet needs &amp;amp;amp; to be used&lt;p&gt;';

Tested with -master and -developer today.

**Comment by GMTA** [comment]
Of course, when the API works like every other API out there in the world, the following snippet should be the one to work:

> '<p>Some well formed HTML snippet needs &amp; to be used<p>';

**Comment by chrispen** [comment]
Hi
I did the following:
<h4> Introduction &amp; </h4>;

But i am getting illegal chars error message. However, it works when i double escape it.
I am  new to phpword. May someone brief me why this is not working as expected.
Thank you.
chris

**Comment by chrispen** [comment]
Hi
I made the following changes to addHtml(), line 51-52
$html = str_replace(array('&'), '&amp;amp;', $html);
 $html = str_replace(array('_lt_', '_gt_', '_amp_'), array('&lt;', '&gt;', '&amp;amp;'), $html);
@klompenrunner ; And it's now working.
Thank you
chrispen

**Comment by anrikun** [comment]
Same issue here.
Any HTML containing entity &amp;amp; added through addHtml() breaks document.xml.

**Comment by dzafel** [comment]
+1
`$amp;` does not work, breaks document.xml **BUT** also `&` does not work, breaks document.xml as well. What the hell?

**Comment by dzafel** [comment]
I think I found the issue, it's because authors of PHPWord use `DOMDocument::loadXML` in `\PhpOffice\PhpWord\Shared\Html` class. It replaces `&amp;` back to `&`, and then it's added to Word document, that's obviously an error in XML file, please replace entities with something like `~amp~` before `loadXML` and then replace them back to `&amp;` when you get the raw text using `->nodeValue`, right now you're doing it all before `loadXML` which is wrong. I can't find any workaround other than just creating a fixed clone of Html class and use it instead of the original one.

**Comment by GMTA** [comment]
@dzafel The author thinks you should apply escaping yourself, even if that is impossible, such as in your case. Please see issue #401 for a despressing discussion I had with @RomanSyroeshko about why he thinks PHPWord should work differently from every other library ever developed.

You'll probably be better off forking this repository and making the necessary changes yourself.

**Comment by dzafel** [comment]
@GMTA yeah, I saw that thread. Unfortunatelly I don't have any time to wait for a fix, I made a dirty-fix for now - I cloned `Html` class, but I also found `pandoc` software and I think I'm going to switch to it, PHPWord is way too unstable, even if they "consider introducing escaping components in the next release"...

**Comment by RomanSyroeshko** [comment]
To those who prefer to argue and to complain instead of doing something with his hands making thus the world better.

a) If you're brave, smart and experienced enough to define how a good open-source library should evolve, prove that and ask to be a part of the team. Many teams will be glad to have such professional. As for the PHPWord. As you can see by commit history, it experiences great lack of professional care. It needs you! So, you can try right here, right now.

b) If you're maverick and working with existing team is not and option for you, you can always maintain a fork. God bless GitHub, because it allows us to do that in a few steps!

c) If you're disappointed by people who maintain a library and don't like its codebase too, there is another option. Build your own next-gen library using all best practices, cutting-edge technologies and standards. I think this is the best option, because in a couple days with a few lines of code you can build a library which really rocks.

If you're not following a), not following b) and not following c), all of your words are just "blah-blah blah-blah blah". Please, stop wasting other peoples' time. Believe or not, but that makes the world better too.

Thanks. Nothing personal.

**Comment by GMTA** [comment]
@RomanSyroeshko You left out option "d", which is: fix the issue and submit a patch or pull request. But according to #401 (and the deleted comments therein) you have already chosen a direction for PHPWord and are not diverting from this path.

I wonder what you would do if the PHP dev team suddenly decided to remove a feature you needed for PHPWord, without the possibility to work around it or fix it easily. My guess? You would complain. And hope that they do not delete your comments. And if all that doesn't work, you would maybe, *possibly*, try to fix the issue yourself by joining the dev team - after which you'll be confronted with the attitude of the developers that led you there in the first place.

So either close these issues with a template message stating that you do not care about fixing this issue because you do not see it as an issue, or acknowledge that there is a problem that can be fixed in any of X ways. Please stop with the "blah-blah" that has nothing to do with the issue at hand.

**Comment by RomanSyroeshko** [comment]
Hi @klompenrunner,
This is currently resolved in scope of #483 (have a look at `develop` branch).

Thanks for the feedback.
