### ISSUE TITLE
Text Align not correct work

### ISSUE THREAD

**Issue by Ryuzakix3** [PHPOffice/PHPWord#704]
When you use addText and set the align to "start" or "left" in the paragraphstyle than is the word file corrupt but when you use only "end" or nothing as align, than is the word file ok.

**Comment by Sohorev** [comment]
When you use addText and set the align to \PhpOffice\PhpWord\SimpleType\Jc::END alignment not works. For example change alignment in Sample_08_ParagraphPagination.php to \PhpOffice\PhpWord\SimpleType\Jc::END and view bug.

У меня выравнивание текста справа не работает - проверить можно легко в файле Sample_08_ParagraphPagination.php указать выравнивание \PhpOffice\PhpWord\SimpleType\Jc::END и увидеть, что выровнено слева. Выравнивание не работает не в простом тексте, ни в тексте внутри ячейки таблицы.

**Comment by RomanSyroeshko** [comment]
@Ryuzakix3, could you, please, provide a code sample to reproduce the problem? I played with `Sample_08_ParagraphPagination.php` a bit, but the result file opens well.

Thanks.

**Comment by RomanSyroeshko** [comment]
@Sohorev, take a look [here](https://www.dropbox.com/s/ee1b3j8pvgvzbs9/Sample_08_ParagraphPagination.php?dl=0) and [here](https://www.dropbox.com/s/jq91atb4ysuxx2i/Sample_08_ParagraphPagination.docx?dl=0). It works. Any details?

**Comment by Sohorev** [comment]
Generated document is not displayed correctly in ms word 2007, and kingsoft office. But in libreoffice displayed normal

Вы меня поняли совершенно правильно, именно так и делаю.
Пример скачал, выполнил - уточнение такое выравнивание работает, только если результат открыватьчерез libreoffice (под linux). В MsWord 2007 (под виндой) и kingsoft office (под linux) выравнено слева т.е. не верно.

**Comment by RomanSyroeshko** [comment]
Unfortunately, I do not have Microsoft Office installation available to test on, so I tried WPS Office 2016 and found one interesting thing. WPS Office Writer uses `right` value for horizontal alignment. As a matter of fact, [OOXML standard](http://standards.iso.org/ittf/PubliclyAvailableStandards/c061750_ISO_IEC_29500-1_2012.zip) does not allow such value (see p.1396). It requires using value `end`. I thought they maybe using previous versions of the standard. So I looked into ECMA-376 Second Edition (equals to ISO/IEC 29500:2008 standard) and failed again. Only in the very first edition of ECMA-376 I found `right` instead of `end`. It seems WPS Office Writer creates documents based on 2006 year standard. :disappointed: 

I will take some time to find out what to do with that stuff.

Thanks for the report!

**Comment by RomanSyroeshko** [comment]
@Sohorev, I pushed some changes to `develop` branch.

Please, use `Jc::RIGHT` in your case. Microsoft Word 2007 knows nothing about ISO/IEC-29500:2008 standard, so it relies on the older one (ECMA-376 1st Edition). See my comments in `Jc` and `JcTable` classes for additional information.

Good luck!
